# Reasons why a client was disconnected.
DISCONNECT_NORMAL = 0
DISCONNECT_END_OF_PACKET = 1
DISCONNECT_LOCAL_MODE = 2
DISCONNECT_KICK = 3
DISCONNECT_MESSAGE_ERROR = 4
DISCONNECT_IP_BAN = 5
DISCONNECT_PRIVATE_MODE = 6
DISCONNECT_MAX_CLIENTS = 7
DISCONNECT_TIMEOUT = 8
DISCONNECT_OVERFLOW = 9
DISCONNECT_PASSWORD = 10
